# Generated by Django 3.2.8 on 2021-10-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='NameProduct')),
                ('description', models.CharField(max_length=500, verbose_name='Descriptions')),
                ('image', models.URLField()),
                ('amount', models.IntegerField(default=5)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
